### PR TITLE
Added AMOLED theme

### LINKED ISSUE #5: [Feature]: AMOLED theme
### What feature do you want to add?

Add AMOLED theming for those who have AMOLED devices!

### Why do you want to have this feature?

To enrich the viewing experiences on said devices!

### Any other details to share?

viva sudo-flix

### PR DESCRIPTION
**Pull request by userkace**
This pull request resolves #5 [Feature: AMOLED theme](https://github.com/sussy-code/smov/issues/5)

 - [✔️] I have read and agreed to the [code of conduct](https://github.com/movie-web/movie-web/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [✔️] I have read and complied with the [contributing guidelines](https://github.com/movie-web/movie-web/blob/dev/.github/CONTRIBUTING.md).
 - [✔️] What I'm implementing was assigned to me and is an [approved issue](https://github.com/movie-web/movie-web/issues?q=is%3Aopen+is%3Aissue+label%3Aapproved). For reference, please take a look at our [GitHub projects](https://github.com/movie-web/movie-web/projects).
 - [✔️] I have tested all of my changes.

### CODE REVIEW

**Comment by userkace** [comment]
i can't seem to find where the theme selections are created, so i just added the colors for now

**Comment by sussy-code** [comment]
yea so theres some issues namely a loss of themes this is your pr:
image
this is current sudo-flix:
image
and also fix the title of the theme!
image

**Comment by userkace** [comment]
That's odd none of that should be gone as only the themes were modified ill update later

**Comment by sussy-code** [comment]
also see the context on discord for more issues https://discord.com/channels/1232477552665428018/1232494666193174559/1232889400338153505

**Pull request closed without merging**
