### PR TITLE
Trying to fix turnstile

### PR DESCRIPTION
**Pull request by vikas5914**
This pull request resolves #XXX

 - [x] I have read and agreed to the [code of conduct](https://github.com/sussy-code/smov/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/sussy-code/smov/blob/dev/.github/CONTRIBUTING.md).
 - [x] I have tested all of my changes.
 - Enter discord user: `Marcus5914` (we require this for the contributor role)

### CODE REVIEW

**Comment by ztpn** [comment]
This most likely won't fix it, the problem is in the lib or turnstile itself mostly. A flx that will mostly work is having a delay after turnstile is loaded, since it needs some time to initialize

**Comment by vikas5914** [comment]
> This most likely won't fix it; the problem is mostly in the lib or turnstile itself. A flux that will mostly work is having a delay after the turnstile is loaded since it needs some time to initialize

We are not triggering the execution. The new plugin will do so automatically and show the popup. .

**Comment by ztpn** [comment]
I Dunno man, you removed the turnstile dependency, removed the execution, you just fixed a bit of mess that baddev created

**Comment by vikas5914** [comment]
> I Dunno man, you removed the turnstile dependency, removed the execution, you just fixed a bit of mess that baddev created

You need to check the previous comment in this branch. We are using different package for turnstile. https://github.com/marsidev/react-turnstile

**Comment by ztpn** [comment]
> > I Dunno man, you removed the turnstile dependency, removed the execution, you just fixed a bit of mess that baddev created
> 
> You need to check the previous commit in this branch. We are using different package for turnstile. https://github.com/marsidev/react-turnstile

Oh, so I fixed the old one for no reason

**Comment by sussy-code** [comment]
This looks fire

**Pull request merged**
