### PR TITLE
Add setting to make subtitles bold

### PR DESCRIPTION
**Pull request by carince**
- [x] I have read and agreed to the [code of conduct](https://github.com/sussy-code/smov/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/sussy-code/smov/blob/dev/.github/CONTRIBUTING.md).
 - [x] I have tested all of my changes.
 - [x] I love sudo-flix

### CODE REVIEW

**Comment by sussy-code** [comment]
I simply dont see the toggle for this...

**Comment by carince** [comment]
> I simply dont see the toggle for this...

Weird, I see both toggles in the player and in the settings page. Mind if you can double check that you are on the right branch?

**Comment by sussy-code** [comment]
Hello thanks for the reply, can you send a video here of the feature working. Would love to merge this.

**Comment by sussy-code** [comment]
ok ill polish and merge this today.

**Pull request merged**
