### PR TITLE
Some stuff

### PR DESCRIPTION
**Pull request by Digital39999**
This pull request resolves Scrolling on discover page (with a catch), adds option to disable searching for movies if you're not logged in and adds option to disable any new registrations at all.

 - [x] I have read and agreed to the [code of conduct](https://github.com/sussy-code/smov/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/sussy-code/smov/blob/dev/.github/CONTRIBUTING.md).
 - [x] I have tested all of my changes.

### CODE REVIEW

**Comment by Digital39999** [comment]
With all respect, I don't see how I changed the website in any way, and further more its not even actually your website but forked. I have just added something that people who are mostly selfhosting this for private use will find useful, which is literally the case, don't want the option? Fine, don't toggle it on. For the discover page, how have i changed it? By adding top light thing? To just make it look like the rest of such pages? Like 404 and homepage, you don't really make sense, only thing different is removed light that makes whole website bug out on a simple task of scrolling.

**Comment by Digital39999** [comment]
Literally almost 0 difference, objectively 1st is better looking.

- https://665611a0e8a0d263e127c803--lucky-queijadas-fde11a.netlify.app/discover
- https://sudo-flix.lol/discover

**Comment by Digital39999** [comment]
So basically no points to argument mine as to why to keep registration stuff, great. What video?

**Comment by sussy-code** [comment]
oh i forgot the vid i guess🤷‍♂️ i am not gonna argue you over a codebase i control and i don't want the registration thing.

**Comment by Digital39999** [comment]
Sure, we'll see.

**Comment by sussy-code** [comment]
wot?

**Comment by EthanQuarry** [comment]
Oh shit, it's going down

**Comment by sussy-code** [comment]
fr bro like i dont wanna add your shitty registration wall 💀

**Comment by EthanQuarry** [comment]
I will say the UI is beautiful but the UX lowkey stinks. Is it fine if I update some padding and shi, maybe add some skeleton loading states cuz it looks a lil goofy when I boot it up with friends (other than that I love it so much)

**Comment by sussy-code** [comment]
Yes i would love that sounds very nice please open a pr i would love to take a look, also join [discord](https://discord.gg/GXNsz4Wy) so i can make you a contributor

**Comment by EthanQuarry** [comment]
Just joined im ethanq1.

**Comment by Digital39999** [comment]
> fr bro like i dont wanna add your shitty registration wall 💀 

I seriously don't get what's so wrong with it that you're so against.

**Comment by sussy-code** [comment]
idk why you think we want this in our code base just because you want it doesn't mean everyone does. image

**Comment by Digital39999** [comment]
But then again only because you and 10 people don't want, doesn't mean whole world doesn't.

**Comment by sussy-code** [comment]
bro just give up the great thing about open-source is that u can fork it and make your own repository

**Comment by Digital39999** [comment]
Doesn't really work that way if i want to keep it up to date.

image

**Comment by JorrinKievit** [comment]
it kinda does work that way

**Comment by sussy-code** [comment]
this is fucking cancer bro ur a skid learn git merge 💀

**Pull request closed without merging**
