### PR TITLE
working link

### PR DESCRIPTION
**Pull request by quote-therizzler**
yea

This pull request resolves #XXX

 - [ ] I have read and agreed to the [code of conduct](https://github.com/sussy-code/smov/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [ ] I have read and complied with the [contributing guidelines](https://github.com/sussy-code/smov/blob/dev/.github/CONTRIBUTING.md).
 - [ ] I have tested all of my changes.
 - [x] I love sudo-flix

### CODE REVIEW

**Comment by quote-therizzler** [comment]
that's the one from readme

**Comment by quote-therizzler** [comment]
> ### 👷 Deploy request for _iridescent-chaja-1874ea_ pending review.
> [Visit the deploys page to approve it](https://app.netlify.com/sites/iridescent-chaja-1874ea/deploys)
> 
> Name	Link
> 🔨 Latest commit	[964dff8](https://github.com/sussy-code/smov/commit/964dff879742068a5538cd7cd7ea58a4b4eddefa)

stfu

**Review by dihydrocodeine — APPROVED** [review]
Simple link swap, links to the server. All good

**Comment by sussy-code** [comment]
Man like

**Pull request closed without merging**
