### PR TITLE
Fix scrolling on discover page

### PR DESCRIPTION
**Pull request by leodenham**
This pull request resolves issues with scrolling on the discover page. 

 - [x] I have read and agreed to the [code of conduct](https://github.com/sussy-code/smov/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x] I have read and complied with the [contributing guidelines](https://github.com/sussy-code/smov/blob/dev/.github/CONTRIBUTING.md).
 - [x] I have tested all of my changes.
 - Enter discord user: `lollylegs2`

Before:
- Could not vertically scroll when hovering over movie card
- Could not horizontal scroll without jumping and jank.

After:
- Removed all scroll hijacking.

### CODE REVIEW

**Comment by sussy-code** [comment]
Hi thanks for your PR, this is a difficult issue for me. Please send a video of your new scrolling thingie.

**Comment by leodenham** [comment]
> Hi thanks for your PR, this is a difficult issue for me. Please send a video of your new scrolling thingie.

Sorry for the low resolution, heres a gif:
CleanShot 2024-05-11 at 16 06 02

**Comment by TecEash1** [comment]
Ayy u managed to do it

**Comment by sussy-code** [comment]
Still cant scroll using mouse wheel, this is a must bc it is rlly cool!

**Comment by sussy-code** [comment]
Still unresolved.

**Comment by returnkirbo** [comment]
Hey, I was looking at the code for this pull request and I had noticed that you can't scroll using mouse wheel simply because a piece of the code was removed that removed the handling of the wheel. ``onMouseEnter`` & ``onMouseLeave`` is also needed to handle the changing of overflow states. 

```typescript
onMouseEnter={handleMouseEnter}
onMouseLeave={handleMouseLeave}
onWheel={(e) => handleWheel(e, categorySlug)} 
```

Drag Racing

**Comment by sussy-code** [comment]
huh ok i will reopen

**Pull request closed without merging**
