### PR TITLE
Hold to edit bookmarks

### PR DESCRIPTION
**Pull request by Pasithea0**
added the ability to hold to edit
added floating button to finish

https://github.com/user-attachments/assets/e91111ae-e62e-4ce6-abe3-ba1cc4c37dff

 - [ x] I have read and agreed to the [code of conduct](https://github.com/sussy-code/smov/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x ] I have read and complied with the [contributing guidelines](https://github.com/sussy-code/smov/blob/dev/.github/CONTRIBUTING.md).
 - [ x] I have tested all of my changes.
 - Enter discord user: `.pasithea` (we require this for the contributor role)

### CODE REVIEW

**Comment by Pasithea0** [comment]
https://main.envyflix.pages.dev/

**Comment by Pasithea0** [comment]
Kinda bugged on mobile because of user selection. I think I can fix that easy, but don't merge yet

**Comment by Pasithea0** [comment]
Ok that worked, it's good now.
I also made the button have a green border so it's slightly easier to see. 
Honestly couldn't figure out how to get the theme accent color so green works.

https://main.envyflix.pages.dev/

**Comment by ztpn** [comment]
It's still broken on mobile. Here's a suggestion just scrap this old editing flow and use the bookmark button on mediaCard instead that also makes it more user friendly

**Comment by Pasithea0** [comment]
It used to be like that but it was removed because it was too cluttered

**Comment by ztpn** [comment]
> It used to be like that but it was removed because it was too cluttered

what? the bookmark button was never completed, on mw we had decided to replace the editing flow with bookmark button but before it could happen we got a c&d

**Comment by Pasithea0** [comment]
I implemented it into sudoflix a while ago but BadDev didn't agree with how it looked. 
Screenshot 2024-07-27 at 10 33 51 AM

While I could have removed it completly, or the editing system as BadDev suggested, I implemented the solution:  "searchQuery.length > 0"  to show the bookmark button only when searching. This solution offers the best of both worlds for the user.

Here you can see it always enabled (as origonaly proposed), vs the change I made to only show it when searching.
https://github.com/user-attachments/assets/7367340b-6052-4502-92a3-82c139a55c0c

**Pull request closed without merging**
