### PR TITLE
Added "Go Home" button to ErrorPart.tsx

### PR DESCRIPTION
**Pull request by Pasithea0**
Just a simple fix

 - [ x] I have read and agreed to the [code of conduct](https://github.com/sussy-code/smov/blob/dev/.github/CODE_OF_CONDUCT.md).
 - [x ] I have read and complied with the [contributing guidelines](https://github.com/sussy-code/smov/blob/dev/.github/CONTRIBUTING.md).
 - [ x] I have tested all of my changes.
 - Enter discord user: `.pasithea` (we require this for the contributor role)

### CODE REVIEW

**Comment by itzCozi** [comment]
Lemme get a review link

**Comment by Pasithea0** [comment]
https://home-on-error.envyflix.pages.dev/

**Comment by Pasithea0** [comment]
Although the only time I have seen this error page is when self hosting. I'll send screenshots in a sec

**Comment by ztpn** [comment]
> Although the only time I have seen this error page is when self hosting. I'll send screenshots in a sec

if im not wrong you've change the base errorpart which is used by every error and icl go home doesn't make any sence on ALOT of errors

**Comment by Pasithea0** [comment]
I kept getting this error when testing some changes and it wouldn't let me go back even with back arrow. I haven't seen this affect any other error pages, only this one weird case where running it locally.

Here's before and after the change.

Screenshot 2024-07-28 at 10 57 58 AM
Screenshot 2024-07-28 at 10 57 42 AM

**Comment by ztpn** [comment]
> I kept getting this error when testing some changes and it wouldn't let me go back even with back arrow. I haven't seen this affect any other error pages, only this one weird case where running it locally.
> 
> Here's before and after the change.
> 
> Screenshot 2024-07-28 at 10 57 58 AM Screenshot 2024-07-28 at 10 57 42 AM

i found one example 
IMG_1018
This is caused throughout the app so here the go home button will look very dumb imo.
A reload page button makes more sense?

**Pull request closed without merging**
